### ISSUE TITLE
Nightscout: Show raw along with calculated

### ISSUE THREAD

**Issue by kevinconroy** [kevinconroy/cgm-simple-spark#12]
Show raw in the spot where clean appears now.

https://www.facebook.com/groups/cgminthecloud/permalink/937934456327811/?comment_id=937961959658394&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by hackingtype1** [comment]
This is more of an education opportunity - none of the data is truly "raw." What people may be asking for is the Nightscout-equation derived EGV in addition to the Dexcom derived EGV when the noise is classified as "clean." When the noise is "clean" both values are being derived from the same sensor value, it is only the calculation that differs. I defer to Dexcom's V&V'd method, and not our "best guess" at what they are doing (which is what the Nightscout-equation is).

I've also seen "raw" defined as [sensor value]/1000
I don't do this because it assumes a lot about the slope & intercept, of the sensor which may simply not be true. It is potentially very dangerous. Right now, my blood sugar is 65, and the raw sensor value is 130,000. Using the /1000 calculation would give me an EGV that may not prompt the safest response.

**Comment by kevinconroy** [comment]
To keep UI clean - and since Share doesn't support this - going to close.
